=== Malnormalulos-git/Programing/XML/lab_6_3/src/main/java/com/mycompany/lab_6_3/dtd_resume.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!ELEMENT resume (lastName, firstName, initials?, bday,
 edu+, job*, image)>
<!ELEMENT lastName (#PCDATA)>
<!ELEMENT firstName (#PCDATA)>
<!ELEMENT initials (#PCDATA)>
<!ELEMENT bday (#PCDATA)>
<!ELEMENT edu (#PCDATA)>
<!ATTLIST edu
 level (school|college|university|academy) 'university'>
<!ELEMENT job (company,post,start,end)>
<!ELEMENT company (#PCDATA)>
<!ELEMENT post (#PCDATA)>
<!ELEMENT exp (#PCDATA)>
<!ELEMENT start (#PCDATA)>
<!ELEMENT end (#PCDATA)>
<!ELEMENT image (#PCDATA)>
<!ATTLIST image
 href (image1.png|image2.png|image3.png|image4.png) 'image1.png'>

=== Malnormalulos-git/Programing/XML/lab_6_3/src/main/java/com/mycompany/lab_6_3/resume.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE resume SYSTEM "dtd_resume.dtd">
<?xml-stylesheet type="text/xsl" href="xsl_resume.xsl" ?>
<resume>
 <lastName>Петрова</lastName>
 <firstName>Світлана</firstName>
 <initials>Іванівна</initials>
 <bday>26 жовтня 1995</bday>
 <edu level="school">
 Запорізька гімназія №71
 </edu>
 <edu level="college">
 Запорізький радіо колледж,
 Телекомунікації
 </edu>
 <edu level="university">
 НУ Запорізька політехніка, Комп’ютерна інженерія
 </edu>
 <edu level="university">
 КНТУ, Захист інформації
 </edu>

 <job>
 <company>Freshcode</company>
 <post>Java Developer</post>
 <start>25 листопада 2015</start>
 <end>8 червня 2018</end>
 </job>
 <job>
 <company>Lagrange-systems</company>
 <post>Java Developer</post>
 <start>20 червня 2018</start>
 <end>15 січня 2020</end>
 </job>

<image href="image1.png">Рисунок</image>

</resume>
