=== Malnormalulos-git/Programing/XML/lab_6_2/src/main/java/com/mycompany/lab_6_2/xsd_resume.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
 <xs:element name="resume" type="resume"/>
 <xs:complexType name="resume">
 <xs:sequence>
 <xs:element name="lastName" type="xs:string"/>
 <xs:element name="firstName" type="xs:string"/>
 <xs:element name="initials" type="xs:string"
minOccurs="0"/>
 <xs:element name="bday" type="xs:date"/>
 <xs:element name="edu" minOccurs="1" maxOccurs="10">

 <xs:complexType>
 <xs:simpleContent>
 <xs:extension base="xs:string">
 <xs:attribute name="level">
 <!--Визначення типу атрибуту-->
 <xs:simpleType>
 <xs:restriction base="xs:string">
 <xs:enumeration value="school"/>
<xs:enumeration value="college"/>
<xs:enumeration value="university"/>
<xs:enumeration value="academy"/>
 </xs:restriction>
 </xs:simpleType>
 </xs:attribute>
 </xs:extension>
 </xs:simpleContent>
 </xs:complexType>
 </xs:element>

 <xs:element name="job" minOccurs="0" maxOccurs="20">
 <xs:complexType>
 
 
 <xs:sequence>
     
 <xs:element name="company" minOccurs="0" maxOccurs="10">
 <xs:complexType>
 <xs:simpleContent>
 <xs:extension base="xs:string">
 <xs:attribute name="type">
 <xs:simpleType>
 <xs:restriction base="xs:string">
 <xs:enumeration value="VAT"/>
<xs:enumeration value="ВАТ"/>
<xs:enumeration value="TOV"/>
<xs:enumeration value="ТОВ"/>
 </xs:restriction>
 </xs:simpleType>
 </xs:attribute>
 </xs:extension>
 </xs:simpleContent>
 </xs:complexType>
 </xs:element>
 
 <xs:element name="post" type="xs:string"/>
 <xs:element name="start" type="xs:date"/>
 <xs:element name="end" type="xs:date"/>
 </xs:sequence>
 </xs:complexType>
 </xs:element>
 </xs:sequence>
 </xs:complexType>
</xs:schema>

=== Malnormalulos-git/Programing/XML/lab_6_2/src/main/java/com/mycompany/lab_6_2/resume.xml
<?xml version="1.0" encoding="UTF-8"?>
 <resume
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="xsd_resume.xsd">
 <lastName>Іваненко</lastName>
 <firstName>Сергій</firstName>
 <initials>Вікторович</initials>
 <bday>1996-03-16</bday>
 <edu level="school">
 ЗОГ №57 м.Київ
 </edu>
 <edu level="academy">
 Українська Академія Архітектури
 </edu>
 <job>
 <company type="ВАТ">Архіматика</company>
 <post>Головний архітектор</post>
 <start>2019-11-25</start>
 <end>2020-02-20</end>
 </job>

</resume>
