=== Malnormalulos-git/Programing/XML/lab_6_1/src/main/java/com/mycompany/lab_6_1/dtd_resume.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT
 resume (lastName,firstName,initials?,bday,edu+,job*,contact+)>
<!ELEMENT lastName (#PCDATA)>
<!ELEMENT firstName (#PCDATA)>
<!ELEMENT initials (#PCDATA)>
<!ELEMENT bday (#PCDATA)>
<!ELEMENT edu (#PCDATA)>
<!ATTLIST edu
 level (school|college|university|academy) 'university'>
<!ELEMENT job (company,post,start,end)>
<!ELEMENT company (#PCDATA)>
<!ELEMENT post (#PCDATA)>
<!ELEMENT start (#PCDATA)>
<!ELEMENT end (#PCDATA)>
<!ELEMENT contact (#PCDATA)>
<!ATTLIST contact
 type (tel|adress|email|Skype) 'tel'>

=== Malnormalulos-git/Programing/XML/lab_6_1/src/main/java/com/mycompany/lab_6_1/resume.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE resume SYSTEM "dtd_resume.dtd">
 <resume>
 <lastName>Петрова</lastName>
 <firstName>Світлана</firstName>
 <initials>Іванівна</initials>
 <bday>26 жовтня 1995</bday>
 <edu level="school">
 Запорізька гімназія №71
 </edu>
 <edu level="college">
 Запорізький радіо колледж,
 Телекомунікації
 </edu>
 <edu level="university">
 НУ Запорізька політехніка, Комп’ютерна інженерія
 </edu>
 <edu level="university">
 КНТУ, Захист інформації
 </edu>
 <job>
 <company>Freshcode</company>
 <post>Java Developer</post>
 <start>25 листопада 2015</start>
 <end>8 червня 2018</end>
 </job>
 <job>
 <company>Lagrange-systems</company>
 <post>Java Developer</post>
 <start>20 червня 2018</start>
 <end>15 січня 2020</end>
 </job>
<contact type="tel">099-123-45-67</contact>
<contact type="email">my_email@gmail.com</contact>

</resume>
